### ISSUE TITLE
无法游玩

### ISSUE THREAD

**Issue by Dangal2018** [qwq233/HackerWar-Chinese-Translation-Project#1]
emmmmm这个根本不能玩 我进去只有我本地ip 本地备份ip 和 Jmail邮件服务器 没有任何任务 jmail服务器也无法破解
我前几天加你qq就是为了反映这个情况 希望看到能回复我一下 是不是我没有做对 还是可能需要等待10分钟
才能接到第一个任务

**Comment by qwq233** [comment]
已修复 原因可能是git不会自动添加missions/empty
这文件夹里边是空的 所以git可能会直接忽略
是我疏忽了 对不起orz
